### ISSUE TITLE
序列黑色圆点不是顶部对齐

### ISSUE THREAD

**Issue by gaohomway** [lidary-byte/HMarkdown#2]
1. 序列【黑色圆点】不是顶部对齐，并且我的序列是1、2、3识别出来后是【黑色圆点】
2. 在下图中，我给`Markdown`加了`.padding(16)`属性，但是没有作用到右侧`padding`

![Screenshot_2024-08-02T143151](https://github.com/user-attachments/assets/0a670beb-7b5e-42db-b885-28c9521f52a2)

**Comment by lidary-byte** [comment]
好的 预计明天修复

**Comment by lidary-byte** [comment]
有序列表的渲染是正常的 你可以在[这里](https://marked.js.org/demo/?text=内容)测试一下看看能不能正常渲染
