### ISSUE TITLE
文字有溢出的情况

### ISSUE THREAD

**Issue by gaohomway** [lidary-byte/HMarkdown#4]
文字有溢出的情况，如下图所示：

![Screenshot_2024-08-05T165146](https://github.com/user-attachments/assets/bebff8a5-8a20-42fe-87a7-78be3a4a3630)

**Comment by lidary-byte** [comment]
你外层的宽度需要减掉margin

**Comment by gaohomway** [comment]
外层没有加margin。
看了一下源码，在行内加入了【黑色圆点】需要给子组件重新布局，需要增加 `layoutWeight` 属性

没加属性的效果：

![Screenshot_2024-08-06T223952](https://github.com/user-attachments/assets/e7618660-4816-4e15-92bd-f7bf207df818)

添加后的效果：

![Screenshot_2024-08-06T223933](https://github.com/user-attachments/assets/ff5e2a50-4e67-46bf-8fbb-480dd7e89f81)

**Comment by gaohomway** [comment]
这是我修复的位置，你看看有没有更好的修复方式

<img width="821" alt="截屏2024-08-06 下午10 41 11" src="https://github.com/user-attachments/assets/fcc1f778-6060-4e81-a58e-ddf67809f606">

**Comment by lidary-byte** [comment]
这两个问题确实存在，1.0.7版本已修复 估计明天才能审核通过
